bundle_cache: &bundle_cache
  bundle_cache:
    folder: /usr/local/bundle
    fingerprint_script:
      - echo $CIRRUS_OS
      - ruby -v
      - cat Gemfile
      - cat *.gemspec
  install_script:
    - gem update --system --no-document
    - bundle update

remark_task:
  container:
    image: node
  node_modules_cache:
    folder: node_modules
    fingerprint_script:
      - echo $CIRRUS_OS
      - node -v
      - cat package.json
  install_script: npm install

  lint_script: npm run remark

  only_if: ($CIRRUS_BRANCH == 'main') ||
    changesInclude(
      '.cirrus.yaml', '.gitignore', 'package.json', '.remarkrc.yaml', '**.md'
    )

rubocop_task:
  container:
    image: ruby

  <<: *bundle_cache

  lint_script: bundle exec rubocop

  only_if: ($CIRRUS_BRANCH == 'main') ||
    changesInclude(
      '.cirrus.yaml', '.gitignore', 'Gemfile', '.rubocop.yml', '*.gemspec',
      '**.rb', '**.ru'
    )


rspec_task:
  container:
    matrix:
      - image: ruby:2.5
      - image: ruby:2.6
      - image: ruby:2.7

  <<: *bundle_cache

  environment:
    CODECOV_TOKEN: ENCRYPTED[fb8619d670ca47b2f9f0da3096cee1a2fd01df1170dfadf85b6d36292de75de79031d6ef4a70eeca6314e58b4c1a06d9]

  test_script: bundle exec rspec

  only_if: ($CIRRUS_BRANCH == 'main') ||
    changesInclude(
      '.cirrus.yaml', '.gitignore', 'Gemfile', '.rspec', '*.gemspec', 'lib/**',
      'spec/**'
    )
